[package]
name = "social_page_rank"
version = "1.0.0"
authors = []

[addresses]
indexlist_addr='396bdcb593ce7376313dc24b1c1ee27b4a0c5351888b8de50845380ff5b15ee9'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
